name: ChemScI
channels:
  - rdkit
  - tmap
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - scikit-learn
  - pubchempy
  - rdkit
  - pyyaml
  - pytest
  - mhfp
  - tmap
  - tqdm
