package:
  name: chemsci
  version: "0.1.0"

source:
  git_rev: "0.1.0"
  git_url: https://github.com/Bundaberg-Joey/ChemScI.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  license: GPL3
  summary: Flexible API for cheminformatics feature generation

